---
abstract: 'Go where no Perl has gone before!'
author:
  - 'Jim Bacon <jim@nortx.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Thoroughly-Modern-Perl
no_index:
  directory:
    - t
    - inc
requires: {}
version: v0.4.1
